### ISSUE TITLE
Problem With Modded Server

### ISSUE THREAD

**Issue by HinataOuO** [henkelmax/delivery-inc#29]
Hi, I tried to open a server form my computer, and only with your modpack I can't open it, and I have the following error. I install 3 different versions of java and I tried to reinstall all from 0, but alway I have the same error.... I don't now what could I do.
-----------------------------------------------------------------------------------------------------
2021-11-12 16:09:08,031 main WARN Advanced terminal features are not available in this environment
[16:09:08] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher running: args [--gameDir, ., --launchTarget, fmlserver, --fml.forgeVersion, 36.1.0, --fml.mcpVersion, 20210115.111550, --fml.mcVersion, 1.16.5, --fml.forgeGroup, net.minecraftforge, nogui]
[16:09:08] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 8.0.9+86+master.3cf110c starting: java version 16.0.1 by Oracle Corporation
Exception in thread "main" java.lang.IllegalAccessError: class cpw.mods.modlauncher.SecureJarHandler (in unnamed module @0x4de5031f) cannot access class sun.security.util.ManifestEntryVerifier (in module java.base) because module java.base does not export sun.security.util to unnamed module @0x4de5031f
at cpw.mods.modlauncher.SecureJarHandler.lambda$static$1(SecureJarHandler.java:41)
at cpw.mods.modlauncher.api.LamdbaExceptionUtils.uncheck(LamdbaExceptionUtils.java:95)
at cpw.mods.modlauncher.SecureJarHandler.<clinit>(SecureJarHandler.java:41)
at cpw.mods.modlauncher.Launcher.lambda$new$6(Launcher.java:55)
at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
at cpw.mods.modlauncher.api.TypesafeMap.computeIfAbsent(TypesafeMap.java:52)
at cpw.mods.modlauncher.api.TypesafeMap.computeIfAbsent(TypesafeMap.java:47)
at cpw.mods.modlauncher.Environment.computePropertyIfAbsent(Environment.java:62)
at cpw.mods.modlauncher.Launcher.<init>(Launcher.java:55)
at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:63)
at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:60)
at net.minecraftforge.server.ServerMain.main(ServerMain.java:57)
Press any key to continue . . .
--------------------------------------------------------------------------------------------------------------------

**Comment by henkelmax** [comment]
You need Java 8 or 11 for it to work.

**Comment by HinataOuO** [comment]
> You need Java 8 or 11 for it to work.

I already tried to install different version of java.....now I have the 8 version but it doesn't work and there is the same problem...

**Comment by henkelmax** [comment]
Please send me the logs properly.

**Comment by HinataOuO** [comment]
Are these the logs ?
[12Nov2021 18:57:16.409] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher running: args [--gameDir, ., --launchTarget, fmlserver, --fml.forgeVersion, 36.1.0, --fml.mcpVersion, 20210115.111550, --fml.mcVersion, 1.16.5, --fml.forgeGroup, net.minecraftforge, nogui]
[12Nov2021 18:57:16.412] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher 8.0.9+86+master.3cf110c starting: java version 16.0.1 by Oracle Corporation

**Comment by henkelmax** [comment]
You are still using java 16

**Comment by HinataOuO** [comment]
![image](https://user-images.githubusercontent.com/44985853/141528055-66ca6892-02a3-4214-a9af-a9a8f9ab4298.png)
 
But If open java and see info of the build....I see this.... Furthermore if I open minecraft with mod it works, and it wouldn't work if I had java 16 because forge is not supported for it

**Comment by henkelmax** [comment]
Just launch your server with java 8 and it will work.

**Comment by HinataOuO** [comment]
how can I open the server with java 8 ??? I have only this version on pc but I have the same probelm

**Comment by henkelmax** [comment]
Î only provide support for the modpack, not on how to launch a server.
